- command: "{{ bindir }}/apex version"
  register: _version
  changed_when: "_version|failed or not _version.stdout.endswith(' ' + version)"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - get_url:
      url: https://github.com/apex/apex/releases/download/v{{ version }}/apex_{{ ansible_system|lower }}_amd64
      dest: "{{ bindir }}/apex"
      mode: ugo+x
      force: yes
