homebrew_state: present

ansible_version_:        2.3.1.0
apex_version:            0.12.0
chruby_version:          0.3.9
consul_template_version: 0.18.1
consul_version:          0.7.5
direnv_version:          2.11.3
docker_compose_version:  1.11.2
ghq_version:             0.7.4
git_version:             2.13.1
go_version:              1.7.5
hub_version:             2.2.9
jq_version:              "1.5"
node_version:            v6.9.4
packer_version:          0.12.3
peco_version:            0.5.1
python2_version:         2.7.13
python3_version:         3.6.0
ruby_install_version:    0.6.0
ruby_version:            2.4.0
slackcat_version:        "1.1"
terraform_version:       0.9.8
tig_version:             2.1.1
tmux_version:            "2.3"
