chruby:
  version: 0.3.9
consul:
  version: 0.6.3
consul_template:
  version: 0.12.1
direnv:
  version: 2.6.0
docker_compose:
  version: 1.6.0
ghq:
  version: 0.7.2
go:
  version: "1.6"
hub:
  version: 2.2.3
jq:
  version: "1.5"
peco:
  version: 0.3.5
ruby_install:
  version: 0.6.0
tig:
  version: 2.1.1
