- set_fact:
    ndenv_prefix: "{{ anyenv_prefix }}/envs/ndenv"

- command: test -e {{ ndenv_prefix }}
  register: _exists
  changed_when: false
  ignore_errors: true

- when: _exists|failed
  command: anyenv install ndenv
  environment:
    PATH: "{{ anyenv_prefix }}/bin:{{ ansible_env.PATH }}"

- when: not _exists|failed
  command: git pull
  args:
    chdir: "{{ ndenv_prefix }}"
  register: _result
  changed_when: _result.stdout != 'Already up-to-date.'
