- command: test -e {{ anyenv_prefix }}/envs/ndenv
  register: _exists
  changed_when: false
  ignore_errors: true

- command: anyenv install ndenv
  environment:
    PATH: "{{ anyenv_prefix }}/bin:{{ ansible_env.PATH }}"
  when: _exists|failed

- set_fact:
    ndenv_prefix: "{{ anyenv_prefix }}/envs/ndenv"
