- command: "{{ bindir }}/peco --version"
  register: _version
  changed_when: "_version|failed or not _version.stdout.endswith('v' + version)"
  ignore_errors: true
- when: _version.changed
  vars:
    _basename: peco_{{ ansible_system|lower }}_amd64
    _ext: "{{ 'tar.gz' if ansible_system == 'Linux' else 'zip' }}"
  block:
  - file:
      path: /tmp/{{ _basename }}
      state: absent

  - unarchive:
      src: https://github.com/peco/peco/releases/download/v{{ version }}/{{ _basename }}.{{ _ext }}
      dest: /tmp
      remote_src: yes

  - file:
      path: "{{ bindir }}"
      state: directory

  - copy:
      src: /tmp/{{ _basename }}/peco
      dest: "{{ bindir }}"
      mode: ugo+x

  - file:
      path: /tmp/{{ _basename }}
      state: absent
