#!/usr/bin/env bash
set -euo pipefail

if ! command -v git &>/dev/null; then
  sudo dnf group install 'Development Tools' -y
fi

if [[ ! -e ~/dotfiles ]]; then
  git clone https://github.com/m4i/dotfiles.git ~/dotfiles
fi

~/dotfiles/install.sh
