#!/bin/bash -eu

function main() {
  ### XDG_CONFIG_HOME
  cd config
  for file in $(ls -A); do
    run ln -snf "$PWD/$file" ~/.config
  done
  cd ..

  ### dotfiles

  cd dotfiles
  for file in $(ls -A); do
    link_to_dotfile "$file"
  done
  cd ..

  ### misc

  run mkdir -p ~/tmp
  run chmod 0700 ~/tmp
}

function link_to_dotfile() {
  local file="$1"

  local target="$PWD/$file"
  local link=~/"$file"

  if [[ -e  "$link" ]] && [[ ! -L "$link" ]]; then
    run mv "$link" "$link.$(date +%Y%m%dT%H%M%S)"
  fi
  run ln -snf "$target" "$link"
}

function run() {
  echo "$@"
  "$@"
}

cd $(dirname $0)
main
