- command: test -e {{ anyenv_prefix }}/envs/goenv
  register: _exists
  changed_when: false
  ignore_errors: true

- command: anyenv install goenv
  environment:
    PATH: "{{ anyenv_prefix }}/bin:{{ ansible_env.PATH }}"
  when: _exists|failed

- set_fact:
    goenv_prefix: "{{ anyenv_prefix }}/envs/goenv"
