- command: "{{ bindir }}/hub --version"
  register: _version
  changed_when: "_version|failed or not _version.stdout_lines[1].endswith(' ' + version)"
  ignore_errors: true
- when: _version.changed
  vars:
    _basename: hub-{{ ansible_system|lower }}-amd64-{{ version }}
  block:
  - file:
      path: /tmp/{{ _basename }}
      state: absent

  - unarchive:
      src: https://github.com/github/hub/releases/download/v{{ version }}/{{ _basename }}.tgz
      dest: /tmp
      remote_src: yes

  - file:
      path: "{{ bindir }}"
      state: directory

  - copy:
      src: /tmp/{{ _basename }}/bin/hub
      dest: "{{ bindir }}"
      mode: ugo+x

  - file:
      path: "{{ prefix }}/share/zsh/completions"
      state: directory

  - copy:
      src: /tmp/{{ _basename }}/etc/hub.zsh_completion
      dest: "{{ prefix }}/share/zsh/completions/_hub"

  - file:
      path: /tmp/{{ _basename }}
      state: absent
