- command: ls {{ rbenv_prefix }}/versions
  register: _versions
  changed_when: false
  ignore_errors: true

- command: rbenv install {{ ruby.version }}
  environment:
    PATH:       "{{ rbenv_prefix }}/bin:{{ ansible_env.PATH }}"
    RBENV_ROOT: "{{ rbenv_prefix }}"
  when: _versions|failed or not ruby.version in _versions.stdout_lines

- command: cat {{ rbenv_prefix }}/version
  register: _version
  changed_when: false
  ignore_errors: true

- command: rbenv global {{ ruby.version }}
  environment:
    PATH:       "{{ rbenv_prefix }}/bin:{{ ansible_env.PATH }}"
    RBENV_ROOT: "{{ rbenv_prefix }}"
  when: _version|failed or _version.stdout != ruby.version
