# dependency: unzip

- command: "{{ bindir }}/packer version"
  register: _version
  changed_when: "_version|failed or not _version.stdout_lines[0].endswith('v' + version)"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - unarchive:
      src: https://releases.hashicorp.com/packer/{{ version }}/packer_{{ version }}_{{ ansible_system|lower }}_amd64.zip
      dest: "{{ bindir }}"
      remote_src: yes
    # Fail to validate the SSL certificate on Darwin
    when: ansible_system != 'Darwin'
