# dependency: unzip

- command: "{{ bindir }}/consul version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout_lines[0].endswith('v' + consul.version)"
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - unarchive:
      src: https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_{{ ansible_system | lower }}_amd64.zip
      dest: "{{ bindir }}"
      copy: no
    # Fail to validate the SSL certificate on Darwin
    when: ansible_system != 'Darwin'
