# dependency: unzip

- command: "{{ bindir }}/consul-template -version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stderr.find('v' + consul_template.version + ' ')"
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - unarchive:
      src: https://releases.hashicorp.com/consul-template/{{ consul_template.version }}/consul-template_{{ consul_template.version }}_{{ ansible_system | lower }}_amd64.zip
      dest: "{{ bindir }}"
      copy: no
    # Fail to validate the SSL certificate on Darwin
    when: ansible_system != 'Darwin'
