# dependency: unzip

- command: "{{ bindir }}/consul-template -version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stderr.find('v' + version + ' ')"
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - unarchive:
      src: https://releases.hashicorp.com/consul-template/{{ version }}/consul-template_{{ version }}_{{ ansible_system|lower }}_amd64.zip
      dest: "{{ bindir }}"
      remote_src: yes
    # Fail to validate the SSL certificate on Darwin
    when: ansible_system != 'Darwin'
