if [[ -e /home/linuxbrew/.linuxbrew/bin/brew ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# VSCode の Terminal 起動時に zellij を起動する
if [[ "$TERM_PROGRAM" = vscode ]] && [[ -z "$ZELLIJ" ]]; then
  if type zellij-here >/dev/null; then
    zellij-here
  fi
fi
