- command: "{{ bindir }}/slackcat --version"
  register: _version
  changed_when: "_version|failed or _version.stdout.find(' ' + version + ',') == -1"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - get_url:
      url: https://github.com/vektorlab/slackcat/releases/download/v{{ version }}/slackcat-{{ version }}-{{ ansible_system|lower }}-amd64
      dest: "{{ bindir }}/slackcat"
      mode: ugo+x
      force: yes
