# dependency: make

- set_fact:
    _prefix: "{{ prefix }}/ruby-install"

- command: "{{ _prefix }}/bin/ruby-install --version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout.endswith(' ' + version)"
  block:
  - file:
      path: /tmp/ruby-install-{{ version }}
      state: absent

  - unarchive:
      src: https://github.com/postmodern/ruby-install/archive/v{{ version }}.tar.gz
      dest: /tmp
      remote_src: yes

  - file:
      path: "{{ _prefix }}"
      state: absent

  - command: make install
    args:
      chdir: /tmp/ruby-install-{{ version }}
    environment:
      PREFIX: "{{ _prefix }}"

  - file:
      path: /tmp/ruby-install-{{ version }}
      state: absent
