# dependency: make

- set_fact:
    _prefix: "{{ prefix }}/chruby"

- command: "{{ _prefix }}/bin/chruby-exec --version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout.endswith(' ' + version)"
  block:
  - file:
      path: /tmp/chruby-{{ version }}
      state: absent

  - unarchive:
      src: https://github.com/postmodern/chruby/archive/v{{ version }}.tar.gz
      dest: /tmp
      remote_src: yes

  - file:
      path: "{{ _prefix }}"
      state: absent

  - command: make install
    args:
      chdir: /tmp/chruby-{{ version }}
    environment:
      PREFIX: "{{ _prefix }}"

  - file:
      path: /tmp/chruby-{{ version }}
      state: absent
