- command: test -e {{ anyenv_prefix }}/envs/rbenv
  register: _exists
  changed_when: false
  ignore_errors: true

- command: anyenv install rbenv
  environment:
    PATH: "{{ anyenv_prefix }}/bin:{{ ansible_env.PATH }}"
  when: _exists|failed

- set_fact:
    rbenv_prefix: "{{ anyenv_prefix }}/envs/rbenv"
