- command: "{{ bindir }}/jq --version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout == 'jq-' + version"
  vars:
    _arch: "{{ 'osx-amd64' if ansible_system == 'Darwin' else 'linux64' }}"
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - get_url:
      url: https://github.com/stedolan/jq/releases/download/jq-{{ version }}/jq-{{ _arch }}
      dest: "{{ bindir }}/jq"
      mode: ugo+x
      force: yes
