- package:
    name: unzip
  become: yes

- file:
    path: "{{ bindir }}"
    state: directory

- unarchive:
    src: https://releases.hashicorp.com/consul/{{ consul.version }}/consul_{{ consul.version }}_linux_amd64.zip
    dest: "{{ bindir }}"
    copy: no
