- command: "{{ bindir }}/consul-template -version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stderr.endswith('v' + consul_template.version)"
  block:
  - package:
      name: unzip
    become: yes
    when: ansible_system != 'Darwin'

  - file:
      path: "{{ bindir }}"
      state: directory

  - unarchive:
      src: https://releases.hashicorp.com/consul-template/{{ consul_template.version }}/consul-template_{{ consul_template.version }}_{{ ansible_system | lower }}_amd64.zip
      dest: "{{ bindir }}"
      copy: no
    when: ansible_system != 'Darwin'
