- package:
    name: unzip
  become: yes

- file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- unarchive:
    src: https://releases.hashicorp.com/consul-template/{{ consul_template.version }}/consul-template_{{ consul_template.version }}_linux_amd64.zip
    dest: "{{ ansible_env.HOME }}/bin"
    copy: no
    creates: "{{ ansible_env.HOME }}/bin/consul-template"
