- file:
    path: "{{ bindir }}"
    state: directory

- get_url:
    url: https://github.com/zimbatm/direnv/releases/download/v{{ direnv.version }}/direnv.linux-amd64
    dest: "{{ bindir }}/direnv"
    mode: ugo+x
    force: yes
