- file:
    path: "{{ bindir }}"
    state: directory

- get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose.version }}/docker-compose-Linux-x86_64
    dest: "{{ bindir }}/docker-compose"
    mode: ugo+x
    force: yes
