- package:
    name: unzip

- file:
    path: "{{ prefix }}/ghq"
    state: absent

- file:
    path: "{{ prefix }}/ghq"
    state: directory

- unarchive:
    src: https://github.com/motemen/ghq/releases/download/v{{ ghq.version }}/ghq_linux_amd64.zip
    dest: "{{ prefix }}/ghq"
    copy: no

- file:
    path: "{{ bindir }}"
    state: directory

- file:
    path: "{{ bindir }}/ghq"
    src: "{{ prefix }}/ghq/ghq"
    state: link
