- file:
    path: "{{ bindir }}"
    state: directory

- when: ansible_os_family == 'Debian'
  block:
  - apt_repository:
      repo: ppa:git-core/ppa
    become: yes

  - apt:
      name: git
    become: yes

  - copy:
      src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
      dest: "{{ bindir }}"
      remote_src: yes
      mode: ugo+x

- when: ansible_os_family == 'Darwin'
  block:
  - homebrew:
      name: git
      state: "{{ homebrew_state }}"

  - file:
      path: "{{ bindir }}/diff-highlight"
      src: /usr/local/share/git-core/contrib/diff-highlight/diff-highlight
      state: link
