- file:
    path: "{{ prefix }}"
    state: directory

- file:
    path: "{{ prefix }}/go"
    state: absent

- unarchive:
    src: https://storage.googleapis.com/golang/go{{ go.version }}.linux-amd64.tar.gz
    dest: "{{ prefix }}"
    copy: no
