- file:
    path: /tmp/hub-linux-amd64-{{ hub.version }}
    state: absent

- unarchive:
    src: https://github.com/github/hub/releases/download/v{{ hub.version }}/hub-linux-amd64-{{ hub.version }}.tgz
    dest: /tmp
    copy: no

- file:
    path: "{{ bindir }}"
    state: directory

- copy:
    src: /tmp/hub-linux-amd64-{{ hub.version }}/bin/hub
    dest: "{{ bindir }}"
    mode: ugo+x

- file:
    path: "{{ prefix }}/share/zsh/completions"
    state: directory

- copy:
    src: /tmp/hub-linux-amd64-{{ hub.version }}/etc/hub.zsh_completion
    dest: "{{ prefix }}/share/zsh/completions/_hub"

- file:
    path: /tmp/hub-linux-amd64-{{ hub.version }}
    state: absent
