- file:
    path: "{{ bindir }}"
    state: directory

- get_url:
    url: https://github.com/stedolan/jq/releases/download/jq-{{ jq.version }}/jq-linux64
    dest: "{{ bindir }}/jq"
    mode: ugo+x
    force: yes
