- include: packages.yml

- include: chruby.yml
- include: consul-template.yml
- include: consul.yml
- include: direnv.yml
- include: docker-compose.yml
- include: ghq.yml
- include: git.yml
- include: go.yml
- include: hub.yml
- include: jq.yml
- include: nodebrew.yml
- include: peco.yml
- include: ruby-install.yml
- include: terraform.yml
- include: tig.yml
