- apt:
    name: "{{item}}"
  with_items:
    - colordiff
    - libxml2-dev               # nokogiri
    - libxslt-dev               # nokogiri
    - multitail
    - python-mysqldb            # ansible mysql_user
    - tree
    - xtail
    - zlib1g-dev                # nokogiri
  become: yes
  when: ansible_os_family == 'Debian'
