- when: ansible_os_family == 'Debian'
  apt:
    name: "{{item}}"
  with_items:
    - colordiff
    - libxml2-dev               # nokogiri
    - libxslt-dev               # nokogiri
    - multitail
    - python-mysqldb            # ansible mysql_user
    - silversearcher-ag
    - tree
    - xtail
    - zlib1g-dev                # nokogiri
  become: yes

- when: ansible_os_family == 'Darwin'
  block:
  - homebrew:
      update_homebrew: yes

  - homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default(homebrew_state) }}"
      install_options: "{{ item.install_options | default() }}"
    with_items:
      - readline
      - openssl
      - name: openssl
        state: linked
        install_options: force

      - name: findutils
        install_options: with-default-names
      - name: gnu-sed
        install_options: with-default-names
      - name: gnu-tar
        install_options: with-default-names
      - name: homebrew/dupes/diffutils
        install_options: with-default-names
      - name: homebrew/dupes/grep
        install_options: with-default-names

      - ansible
      - colordiff
      - coreutils
      - nkf
      - nmap
      - reattach-to-user-namespace
      - ssh-copy-id
      - the_silver_searcher
      - tree
      - watch
      - xz

  - homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ homebrew_state }}"
    with_items:
      - appcleaner
      - clipy
      - firefox
      - flux
      - google-chrome
      - google-japanese-ime
      - iterm2
      - karabiner
      - mailplane
