- command: ls {{ goenv.prefix }}/versions
  register: _versions
  changed_when: false
  ignore_errors: true

- command: "{{ goenv.command }} install {{ go.version }}"
  when: _versions|failed or not go.version in _versions.stdout_lines

- command: "{{ goenv.command }} global {{ go.version }}"
  when: "lookup('file', goenv.prefix + '/version') != go.version"
