- command: ls {{ goenv_prefix }}/versions
  register: _versions
  changed_when: false
  ignore_errors: true

- command: goenv install {{ go.version }}
  environment:
    PATH:       "{{ goenv_prefix }}/bin:{{ ansible_env.PATH }}"
    GOENV_ROOT: "{{ goenv_prefix }}"
  when: _versions|failed or not go.version in _versions.stdout_lines

- command: cat {{ goenv_prefix }}/version
  register: _version
  changed_when: false
  ignore_errors: true

- command: goenv global {{ go.version }}
  environment:
    PATH:       "{{ goenv_prefix }}/bin:{{ ansible_env.PATH }}"
    GOENV_ROOT: "{{ goenv_prefix }}"
  when: _version|failed or _version.stdout != go.version
