# dependency: libevent-dev libncurses5-dev make

- set_fact:
    _prefix: "{{ prefix }}/tmux"

- command: "{{ _prefix }}/bin/tmux -V"
  register: _version
  changed_when: "_version|failed or not _version.stdout.endswith(' ' + version)"
  ignore_errors: true
- when: _version.changed
  block:
  - when: ansible_os_family == 'Darwin'
    homebrew:
      name: libevent
      state: "{{ homebrew_state }}"

  - file:
      path: /tmp/tmux-{{ version }}
      state: absent

  - unarchive:
      src: https://github.com/tmux/tmux/releases/download/{{ version }}/tmux-{{ version }}.tar.gz
      dest: /tmp
      remote_src: yes

  - command: ./configure prefix={{ _prefix }}
    args:
      chdir: /tmp/tmux-{{ version }}

  - command: make
    args:
      chdir: /tmp/tmux-{{ version }}

  - file:
      path: "{{ _prefix }}"
      state: absent

  - command: make install
    args:
      chdir: /tmp/tmux-{{ version }}

  - file:
      path: /tmp/tmux-{{ version }}
      state: absent
