- command: "{{ bindir }}/direnv version"
  register: _version
  changed_when: "_version|failed or _version.stdout != version"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - get_url:
      url: https://github.com/zimbatm/direnv/releases/download/v{{ version }}/direnv.{{ ansible_system|lower }}-amd64
      dest: "{{ bindir }}/direnv"
      mode: ugo+x
      force: yes
