# dependency: unzip

- command: "{{ bindir }}/ghq --version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout.endswith(' ' + ghq.version)"
  block:
  - file:
      path: /tmp/ghq
      state: absent

  - file:
      path: /tmp/ghq
      state: directory

  - unarchive:
      src: https://github.com/motemen/ghq/releases/download/v{{ ghq.version }}/ghq_{{ ansible_system | lower }}_amd64.zip
      dest: /tmp/ghq
      copy: no

  - file:
      path: "{{ bindir }}"
      state: directory

  - copy:
      src: /tmp/ghq/ghq
      dest: "{{ bindir }}"
      mode: ugo+x

  - file:
      path: "{{ prefix }}/share/zsh/completions"
      state: directory

  - copy:
      src: /tmp/ghq/zsh/_ghq
      dest: "{{ prefix }}/share/zsh/completions"

  - file:
      path: /tmp/ghq
      state: absent
