"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = "$all$fill$time$line_break$directory$character"

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[directory]
truncation_length = 0
truncate_to_repo = true

[fill]
symbol = " "

[hostname]
format = "[@$hostname]($style) "

[time]
disabled = false
format = "[$time]($style)"
#time_format = "%Y-%m-%d %H:%M:%S"
time_format = "%m%dT%H%M%S"

[username]
disabled = true
