- command: "{{ bindir }}/docker-compose version"
  register: _version
  changed_when: "_version|failed or _version.stdout_lines[0].find(' ' + version + ',') == -1"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: "{{ bindir }}"
      state: directory

  - get_url:
      url: https://github.com/docker/compose/releases/download/{{ version }}/docker-compose-{{ ansible_system }}-x86_64
      dest: "{{ bindir }}/docker-compose"
      mode: ugo+x
      force: yes
