- command: ls {{ ndenv.prefix }}/versions
  register: _versions
  changed_when: false
  ignore_errors: true

- command: "{{ ndenv.command }} install v{{ node.version }}"
  when: _versions|failed or not 'v' + node.version in _versions.stdout_lines

- command: "{{ ndenv.command }} global v{{ node.version }}"
  when: "lookup('file', ndenv.prefix + '/version') != 'v' + node.version"
