# dependency: libcurl4-openssl-dev

- command: "{{ prefix }}/git/bin/git --version"
  register: _version
  changed_when: false
  ignore_errors: true
- when: "_version|failed or not _version.stdout.endswith(' ' + git.version)"
  block:
  - file:
      path: /tmp/git-{{ git.version }}
      state: absent

  - unarchive:
      src: https://github.com/git/git/archive/v{{ git.version }}.tar.gz
      dest: /tmp
      remote_src: yes

  - file:
      path: "{{ prefix }}/git"
      state: absent

  - command: make prefix={{ prefix }}/git NO_TCLTK=1 NO_GETTEXT=1 all
    args:
      chdir: /tmp/git-{{ git.version }}

  - command: make prefix={{ prefix }}/git NO_TCLTK=1 NO_GETTEXT=1 install
    args:
      chdir: /tmp/git-{{ git.version }}

  - copy:
      src: /tmp/git-{{ git.version }}/contrib/diff-highlight/diff-highlight
      dest: "{{ prefix }}/git/bin"
      remote_src: yes
      mode: ugo+x

  - file:
      path: /tmp/git-{{ git.version }}
      state: absent
