# dependency: libcurl4-openssl-dev

- set_fact:
    _prefix: "{{ prefix }}/git"

- command: "{{ _prefix }}/bin/git --version"
  register: _version
  changed_when: "_version|failed or not _version.stdout.endswith(' ' + version)"
  ignore_errors: true
- when: _version.changed
  block:
  - file:
      path: /tmp/git-{{ version }}
      state: absent

  - unarchive:
      src: https://github.com/git/git/archive/v{{ version }}.tar.gz
      dest: /tmp
      remote_src: yes

  - command: make prefix={{ _prefix }} NO_TCLTK=1 NO_GETTEXT=1 all
    args:
      chdir: /tmp/git-{{ version }}

  - file:
      path: "{{ _prefix }}"
      state: absent

  - command: make prefix={{ _prefix }} NO_TCLTK=1 NO_GETTEXT=1 install
    args:
      chdir: /tmp/git-{{ version }}

  - copy:
      src: /tmp/git-{{ version }}/contrib/diff-highlight/diff-highlight
      dest: "{{ _prefix }}/bin"
      remote_src: yes
      mode: ugo+x

  - file:
      path: /tmp/git-{{ version }}
      state: absent
