#!/bin/bash

set -eu

function main() {
  ### dotfiles

  cd dotfiles
  for file in $(ls -A); do
    if [[ "$file" = .config ]]; then
      for _file in $(ls -A "$file"); do
        link_to_dotfile "$file/$_file"
      done
    else
      link_to_dotfile "$file"
    fi
  done
  cd ..

  ### misc

  run mkdir -p ~/tmp
  run chmod 0700 ~/tmp
}

function link_to_dotfile() {
  local file="$1"

  local target="$PWD/$file"
  local link=~/"$file"

  if [[ -e  "$link" ]] && [[ ! -L "$link" ]]; then
    run mv "$link" "$link.$(date +%Y%m%dT%H%M%S)"
  fi
  run ln -snf "$target" "$link"
}

function run() {
  echo "$@"
  "$@"
}

cd $(dirname $0)/..
main
